.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. briskcoin_qt test_briskcoin_qt
clean: FORCE
	$(MAKE) -C .. briskcoin_qt_clean test_briskcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_briskcoin_qt_check
briskcoin-qt briskcoin-qt.exe: FORCE
	 $(MAKE) -C .. briskcoin_qt
apk: FORCE
	$(MAKE) -C .. briskcoin_qt_apk
